apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest-core.fullname" . }}
  labels:
    {{- include "tracetest-core.labels" . | nindent 4 }}
data:
  TRACETEST_ENDPOINT_UI: "{{ include "tracetest-common.url" .Values.global.urls.web }}"
  TRACETEST_ENDPOINT_API: "{{ include "tracetest-common.url" .Values.global.urls.api }}"
  TRACETEST_ENDPOINT_AGENTS: "{{ .Values.global.urls.controlPlane.hostname }}:{{ .Values.global.urls.controlPlane.port }}"
  config.yaml: |-
    nats:
      endpoint: {{ include "tracetest-common.nats_endpoint" . }}

    telemetry:
      profiler:
        name: tracetest
        enabled: {{ .Values.config.profiler.enabled }}
        samplingRate: {{ .Values.config.profiler.samplingRate }}
        endpoint: {{ .Values.config.profiler.endpoint }}
        environment: {{ .Values.config.profiler.environment }}
      # exporters:
      #   collector:
      #     exporter:
      #       collector:
      #         endpoint: collector-opentelemetry-collector.otel:4318
      #       type: collector
      #     metricsReaderInterval: 60s
      #     batchTimeout: 5s
      #     sampling: 50
      #     serviceName: tracetest
    server:
      httpPort: 11633
      # telemetry:
      #   exporter: collector

  provisioning.yaml: |-
      ---
      type: Config
      spec:
        analyticsEnabled: false
