---
apiVersion: v1
kind: Secret
metadata:
  name: oss-postgres-credentials
  labels:
    {{- include "tracetest-core.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.global.postgresql.auth.host | b64enc }}
  user: {{ .Values.global.postgresql.auth.username | b64enc }}
  password: {{ .Values.global.postgresql.auth.password | b64enc }}
  dbname: {{ .Values.global.postgresql.auth.database | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: oss-secrets
  labels:
    {{- include "tracetest-core.labels" . | nindent 4 }}
type: Opaque
data:
  tracetestAnalyticsServerKey: {{ .Values.config.tracetestAnalyticsServerKey | b64enc }}
  tracetestSecurityEncryptionKey: {{ .Values.config.tracetestSecurityEncryptionKey | b64enc }}
  license: "{{ .Values.global.licenseKey | b64enc }}"
