---
apiVersion: v1
kind: Secret
metadata:
  name: oss-postgres-credentials
  labels:
    {{- include "tracetest-core.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.postgres.host | b64enc }}
  user: {{ .Values.postgres.user | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
  dbname: {{ .Values.postgres.dbname | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: oss-secrets
  labels:
    {{- include "tracetest-core.labels" . | nindent 4 }}
type: Opaque
data:
  tracetestAnalyticsServerKey: {{ .Values.config.tracetestAnalyticsServerKey | b64enc }}
  tracetestSecurityEncryptionKey: {{ .Values.config.tracetestSecurityEncryptionKey | b64enc }}
