apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracetest-core.fullname" . }}
  labels:
    {{- include "tracetest-core.labels" . | nindent 4 }}

spec:
  type: ClusterIP
  ports:
    - name: core-api-http
      targetPort: http
      protocol: TCP
      port: {{ .Values.server.httpPort }}
    - name: grpc-collector-entrypoint
      protocol: TCP
      port: {{ .Values.server.otlpGrpcPort }}
      targetPort: 4317
  selector:
    {{- include "tracetest-core.selectorLabels" . | nindent 4 }}
    tracetest/component: api
