apiVersion: v2
name: tracetest-onprem
description: A Helm chart for tracetest On Prem
type: application
version: v1.117.0
dependencies:
- name: tracetest-frontend
  version: v1.16.0
  repository: file://../tracetest-frontend
  condition: tracetest-frontend.enabled
- name: tracetest-core
  version: v1.34.0
  repository: file://../tracetest-core
  condition: tracetest-core.enabled
- name: tracetest-cloud
  version: v1.39.0
  repository: file://../tracetest-cloud
  condition: tracetest-cloud.enabled
- name: tracetest-agent-operator
  version: v1.21.0
  repository: file://../tracetest-agent-operator
  condition: tracetest-agent-operator.enabled
- name: tracetest-monitor-operator
  version: v1.14.0
  repository: file://../tracetest-monitor-operator
  condition: tracetest-monitor-operator.enabled
- name: tracetest-public-endpoint
  version: v1.2.0
  repository: file://../tracetest-public-endpoint
  condition: tracetest-public-endpoint.enabled
- name: tracetest-auth
  version: v1.36.0
  repository: file://../tracetest-auth
  condition: tracetest-auth.enabled
- name: tracetest-common
  version: v1.5.0
  repository: file://../tracetest-common
- name: nats
  version: 1.1.11
  repository: https://nats-io.github.io/k8s/helm/charts/
  condition: nats.enabled
maintainers:
- name: tracetest
  url: https://tracetest.io
icon: https://cdn.prod.website-files.com/625f135a8e554e44ad158913/625f1d8ab2348b3c4e3fa870_logo.svg
home: https://github.com/kubeshop/tracetest-cloud-charts
