apiVersion: v2
name: tracetest-onprem
description: A Helm chart for tracetest On Prem
type: application
version: v1.30.0
dependencies:
- name: tracetest-frontend
  version: v1.6.0
  repository: file://../tracetest-frontend
- name: tracetest-core
  version: v1.14.0
  repository: file://../tracetest-core
- name: tracetest-cloud
  version: v1.18.0
  repository: file://../tracetest-cloud
- name: tracetest-agent-operator
  version: v1.10.0
  repository: file://../tracetest-agent-operator
- name: tracetest-monitor-operator
  version: v1.6.0
  repository: file://../tracetest-monitor-operator
- name: tracetest-auth
  version: v1.14.0
  repository: file://../tracetest-auth
- name: nats
  version: 1.1.11
  repository: https://nats-io.github.io/k8s/helm/charts/
  condition: nats.enabled
maintainers:
- name: tracetest
  url: https://tracetest.io
icon: https://cdn.prod.website-files.com/625f135a8e554e44ad158913/625f1d8ab2348b3c4e3fa870_logo.svg
home: https://github.com/kubeshop/tracetest-cloud-charts
