global:
  licenseKey: ""
  
  imagePullSecret: ""
  tracetestImageRegistry: ""

  sso:
    google:
      clientID: "123"
      clientSecret: "123"
    github:
      clientID: "Ov23li8WMwQlvjFNNiCy"
      clientSecret: "e317c15e43909757d1e75e78373d130c374f6601"

  # If you don't want to use the default NATS server, you can specify your own NATS server here
  # natsEndpointOverride: "://nats:4222"

  postgresql:
    auth:
      host: "postgres"
      username: "postgres"
      password: "postgres"
      database: "tracetest"
      port: "5432"
    
  mongodb:
    auth:
      protocol: "mongodb"
      host: ""
      username: ""
      password: ""
      database: ""
      options: {}

  
  urls:
    protocol: &protocol "https"
    port: &port "443"
    rootDomain: &rootDomain "tracetest.localdev"
    cookieDomain: *rootDomain
    
    web:
      protocol: *protocol
      hostname: *rootDomain
      port: *port
      path: "/"
    
    api:
      protocol: *protocol
      hostname: *rootDomain
      port: *port
      path: "/api"

    auth:
      protocol: *protocol
      hostname: *rootDomain
      port: *port
      path: "/api"
    
    agents:
      domain: *rootDomain
      port: *port
    
    controlPlane:
      protocol: *protocol
      hostname: *rootDomain
      port: *port
      path: "/"

nats:
  enabled: true
  
  config:
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 10Gi
      memoryStore:
          enabled: true
          maxSize: 1Gi

    natsBox:
      container:
        env:
          # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
          # should be ~90% of memory limit
          GOMEMLIMIT: 900MiB
        merge:
          # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
          resources:
            requests:
              cpu: 250m # one entire CPU
              memory: 1Gi
            limits:
              memory: 1Gi

