global:
  imagePullSecret: "ghcr-secret" # TODO: set to blank

  nats:
    endpoint: "nats://nats:4222"

  postgresql:
    auth:
      host: "postgres"
      username: "postgres"
      password: "postgres"
      database: "tracetest"
    
  mongodb:
    dsn: &mongoDSN "mongodsn"

  urls:
    webUIUrl: &webUrl "app.tracetest.io"
    apiUrl: &apiUrl "api.tracetest.io"
    controlPlaneUrl: &controlPlaneUrl "control-plane.tracetest.io"

nats:
  enabled: true
  
  config:
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 10Gi
      memoryStore:
          enabled: true
          maxSize: 1Gi

    natsBox:
      container:
        env:
          # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
          # should be ~90% of memory limit
          GOMEMLIMIT: 900MiB
        merge:
          # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
          resources:
            requests:
              cpu: 250m # one entire CPU
              memory: 1Gi
            limits:
              memory: 1Gi


tracetest-cloud:
  config:
    webUIUrl: *webUrl
    apiUrl: *apiUrl
    controlPlaneUrl: *controlPlaneUrl
    mongodbDSN: *mongoDSN
