global:
  imagePullSecret: "ghcr-secret" # TODO: set to blank

  nats:
    endpoint: "nats://nats:4222"

  postgresql:
    auth:
      host: "postgres"
      username: "postgres"
      password: "postgres"
      database: "tracetest"
      port: "5432"
    
  mongodb:
    dsn: &mongoDSN "mongodsn"

  cookieDomain: &cookieDomain ".example.com"
  
  urls:
    issuerUrl: &issuerUrl https://api.example.com/auth
    baseAuthUrl: &baseAuthUrl https://api.example.com/auth
    defaultBrowserReturnUrl: &defaultBrowserReturnUrl https://web.example.com/
    errorUiUrl: &errorUiUrl https://web.example.com/error
    loginUrl: &loginUrl https://api.example.com/oathkeeper/login
    loginAfterHookUrl: &loginAfterHookUrl https://api.example.com/api/webhook/login
    webUIUrl: &webUrl "https://app.tracetest.io"
    apiUrl: &apiUrl "https://api.tracetest.io"
    controlPlaneUrl: &controlPlaneUrl "https://control-plane.tracetest.io"
    agentsDomain: &agentsDomain "agents.example.com"
  
  secrets:
    cookie: &authSecretCookie
      - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
    cipher: &authSecretCipher
      - 32-LONG-SECRET-NOT-SECURE-AT-ALL

nats:
  enabled: true
  
  config:
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 10Gi
      memoryStore:
          enabled: true
          maxSize: 1Gi

    natsBox:
      container:
        env:
          # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
          # should be ~90% of memory limit
          GOMEMLIMIT: 900MiB
        merge:
          # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
          resources:
            requests:
              cpu: 250m # one entire CPU
              memory: 1Gi
            limits:
              memory: 1Gi


tracetest-cloud:
  config:
    webUIUrl: *webUrl
    apiUrl: *apiUrl
    controlPlaneUrl: *controlPlaneUrl
    mongodbDSN: *mongoDSN
