global:
  # License Key provided by Tracetest team to run this instance. Default: `""`
  licenseKey: ""
  
  # This value defines if clients should expect a valid SSL certificate from the server. If you are using a self-signed certificate, you should set this to false. Default: `true`
  validCertificate: true
  
  # Pull secrets name used to fetch images from a private registry if needed. If set empty, this chart will use the public registry. For more details see: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ Default: `""`
  imagePullSecret: ""
  # Registry name used to fetch images. If set empty, this chart will use the public registry. For more details see: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ Default: `""`
  tracetestImageRegistry: ""

  sso:
    google:
      # Google OAuth2 client ID. You can get these from the Google Developer Console. Default: `""`
      clientID: "" 
      # Google OAuth2 secret. You can get these from the Google Developer Console. Default: `""`
      clientSecret: ""
    github:
      # Github OAuth2 client ID. You can get these from the Github Developer Console. Default: `"example client ID"`
      clientID: "Ov23li8WMwQlvjFNNiCy"
      # Github OAuth2 secret. You can get these from the Github Developer Console. Default: `"example client secret"`
      clientSecret: "e317c15e43909757d1e75e78373d130c374f6601"

  # If you don't want to use the default NATS server, you can specify your own NATS server here
  # natsEndpointOverride: "://nats:4222"

  postgresql:
    auth:
      # Postgres host address. Default: `""`
      host: ""
      # Postgres username that Tracetest APIs will use. Default: `""`
      username: ""
      # Postgres password that Tracetest APIs will use. Default: `""`
      password: ""
      # Postgres database name for Tracetest OnPrem. Default: `"tracetest"`
      database: "tracetest"
      # Postgres port. Default: `"5432"`
      port: "5432"
    
  mongodb:
    auth:
      # MongoDB connection protocol. Default: `"mongodb"`
      protocol: "mongodb"
      # MongoDB host address. Default: `""`
      host: ""
      # MongoDB username that Tracetest APIs will use. Default: `""`
      username: ""
      # MongoDB password that Tracetest APIs will use. Default: `""`
      password: ""
      # MongoDB database name for Tracetest OnPrem. Default: `"tracetest"`
      database: ""
      # MongoDB connection options as a key-value object. Default: `"{}"`
      options: {}

  
  # URLs section with addresses used by clients to connect to the Tracetest OnPrem instance
  urls:
    protocol: &protocol "https"
    port: &port "30000"
    rootDomain: &rootDomain "tracetest.localdev"
    cookieDomain: *rootDomain
    
    web:
      protocol: *protocol
      hostname: *rootDomain
      port: *port
      path: "/"
    
    api:
      protocol: *protocol
      hostname: *rootDomain
      port: *port
      path: "/api"

    auth:
      protocol: *protocol
      hostname: *rootDomain
      port: *port
      path: "/auth"
    
    agents:
      domain: *rootDomain
      port: *port
    
    controlPlane:
      protocol: *protocol
      hostname: *rootDomain
      port: *port
      path: "/"

nats:
  credentials:
    username: admin

  enabled: true

  natsBox:
    enabled: false

  config:
    cluster:
      enabled: true
      replicas: 3
    jetstream:
      enabled: true
      fileStore:
        pvc:
          size: 10Gi
      memoryStore:
        enabled: true
        maxSize: 1Gi
    merge:
      accounts:
        $SYS:
          users:
          - {user: << $NATS_ADMIN_USERNAME >>, password: << $NATS_ADMIN_PASSWORD >>}

  container:
    merge:
      env:
      - name: NATS_ADMIN_USERNAME
        valueFrom:
          secretKeyRef:
            name: tracetest-nats-credentials
            key: username
      - name: NATS_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: tracetest-nats-credentials
            key: password
      - name: SERVER_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name

  podTemplate:
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: ScheduleAnyway

tracetest-frontend:
  enabled: true

tracetest-core:
  enabled: true

tracetest-cloud:
  enabled: true

tracetest-agent-operator:
  enabled: true

tracetest-monitor-operator:
  enabled: true

tracetest-auth:
  enabled: true

tracetest-common:
  enabled: true
