global:
  imagePullSecret: "ghcr-secret" # TODO: set to blank

  nats:
    endpoint: "nats://nats:4222"

  postgresql:
    auth:
      host: "postgres"
      username: "postgres"
      password: "postgres"
      database: "tracetest"
      port: "5432"
    
  mongodb:
    dsn: &mongoDSN "mongodsn"

  cookieDomain: &cookieDomain ".example.com"
  
  urls:
    web:
      protocol: "https"
      hostname: "tracetest.localdev"
      port: "30000"
      path: "/"
    
    api:
      protocol: "https"
      hostname: "tracetest.localdev"
      port: "30000"
      path: "/api"

    auth:
      protocol: "https"
      hostname: "tracetest.localdev"
      port: "30000"
      path: "/api"
    
    agents:
      hostname: "tracetest.localdev"
      port: "30000"

    issuerUrl:  https://tracetest.localdev:30000/auth
    baseAuthUrl:  https://tracetest.localdev:30000/auth
    defaultBrowserReturnUrl:  https://tracetest.localdev:30000/
    errorUiUrl:  https://tracetest.localdev:30000/error
    loginUrl:  https://tracetest.localdev:30000/oathkeeper/login
    loginAfterHookUrl:  https://tracetest.localdev:30000/api/webhook/login
    webUIUrl: &webUrl "https://tracetest.localdev:30000"
    apiUrl: &apiUrl "https://tracetest.localdev:30000"
    controlPlaneUrl: &controlPlaneUrl "https://tracetest.localdev:30000"
    agentsDomain: "tracetest.localdev"

nats:
  enabled: true
  
  config:
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 10Gi
      memoryStore:
          enabled: true
          maxSize: 1Gi

    natsBox:
      container:
        env:
          # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
          # should be ~90% of memory limit
          GOMEMLIMIT: 900MiB
        merge:
          # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
          resources:
            requests:
              cpu: 250m # one entire CPU
              memory: 1Gi
            limits:
              memory: 1Gi


tracetest-cloud:
  config:
    webUIUrl: *webUrl
    apiUrl: *apiUrl
    controlPlaneUrl: *controlPlaneUrl
    mongodbDSN: *mongoDSN
