apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-custom-config
  labels:
    {{- include "ory-kratos.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}
