global:
  nats:
    endpoint: "nats://tt-nats-headless:4222"

  postgresql:
    auth:
      host: "ttdeps-postgresql"
      username: "postgres"
      password: "postgres"
      database: "tracetest"


traefik:
  service:
    type: NodePort

  dnsNames:
    - "app.local"
    - "api.local"
    - "*.agents.local"

  tls:
    issuerRef:
      name: issuer-selfsigned
      kind: ClusterIssuer
      group: cert-manager.io