global:
  urls:
    webHostname: "tracetest.localdev"

  nats:
    host: "tt-nats-headless"
    endpoint: "nats://tt-nats-headless:4222"

  postgresql:
    auth:
      host: "ttdeps-postgresql"
      username: "postgres"
      password: "postgres"
      database: "tracetest"

  mongodb:
    auth:
      protocol: "mongodb"
      host: "ttdeps-tracetest-dependencies-mongodb"
      username: "mongodb"
      password: "mongodb"
      database: "tracetest"
      options:
        retryWrites: "true"
        authSource: admin


traefik:
  service:
    type: NodePort

  dnsNames:
    - "tracetest.localdev"

  tls:
    issuerRef:
      name: issuer-selfsigned
      kind: ClusterIssuer
      group: cert-manager.io