apiVersion: v2
name: tracetest-dependencies
description: A Helm chart for tracetest On Prem
type: application
version: v1.1.0

dependencies:
- name: traefik
  version: 24.0.0
  repository: https://traefik.github.io/charts
  condition: traefik.enabled
- name: postgresql
  version: 15.5.7
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: postgresql.enabled

maintainers:
- name: tracetest
  url: https://tracetest.io
icon: https://cdn.prod.website-files.com/625f135a8e554e44ad158913/625f1d8ab2348b3c4e3fa870_logo.svg
home: https://github.com/kubeshop/tracetest-cloud-charts
