apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest-frontend.fullname" . }}
  labels:
    {{- include "tracetest-frontend.labels" . | nindent 4 }}
data:
  REACT_APP_BASE_API_URL: {{ include "tracetest-frontend.URL" .Values.global.urls.api | quote}}
  REACT_APP_ORY_KRATOS_PUBLIC_API_URL: {{ include "tracetest-frontend.URL" .Values.global.urls.auth | quote}}
  REACT_APP_AGENT_URL:  "{{ .Values.global.urls.agents.hostname }}:{{ .Values.global.urls.agents.port }}"
  REACT_APP_UI_URL: {{ include "tracetest-frontend.URL" .Values.global.urls.web | quote}}