{{- if .Values.ingress.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "tracetest-frontend.fullname" . }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.global.urls.webHostname }}`)
    services:
    - kind: Service
      name: {{ include "tracetest-frontend.fullname" . }}
      passHostHeader: true
      port: http
{{- end }}
