pokeshop:
  image:
    repository: kubeshop/demo-pokemon-api
    pullPolicy: Always
    tag: latest

  service:
    type: ClusterIP
    port: 80
    rpcPort: 8082

  # This chart requires Traefik to be installed on the cluster. If you don't have Traefik installed
  # and don't want to install it, make sure to set `ingress.enabled` as `false`. Otherwise, the installation
  # will fail.
  ingress:
    enabled: false
    hostname: pokeshop.localdev

    kafka:
      entrypoint: websecure

  cleanup:
    enabled: false
    cronExpression: "0 0 * * *"

  api:
    resources: {}
    replicaCount: 1
  queueworker:
    resources: {}
    replicaCount: 1
  stream:
    resources: {}
    replicaCount: 1
  streamworker:
    resources: {}
    replicaCount: 1

  env:
    - name: COLLECTOR_ENDPOINT
      value: http://ttdemo-opentelemetry-collector:44317
    - name: DATABASE_URL
      value: postgresql://ashketchum:squirtle123@postgresql:5432/pokeshop
    - name: REDIS_URL
      value: redis-headless
    - name: RABBITMQ_HOST
      value: guest:guest@rabbitmq-headless
    - name: POKE_API_BASE_URL
      value: https://pokeapi.co/api/v2
    - name: HTTP_COLLECTOR_ENDPOINT
      value: https://pokeshop.localdev:30000/v1/traces

postgresql:
  fullnameOverride: postgresql
  auth:
    username: ashketchum
    password: squirtle123
    database: pokeshop
  primary:
    service:
      clusterIP: None

redis:
  fullnameOverride: redis
  architecture: standalone
  auth:
    enabled: false
  master:
    service:
      clusterIP: None

rabbitmq:
  fullnameOverride: rabbitmq
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
  auth:
    username: guest
    password: guest

opentelemetry-collector:
  mode: deployment

  image:
    repository: "otel/opentelemetry-collector-contrib"

  ports:
    otlp:
      enabled: true
      containerPort: 4317
      servicePort: 44317
      hostPort: 44317
      protocol: TCP
      appProtocol: grpc
    otlp-http:
      enabled: true
      containerPort: 4318
      servicePort: 44318
      hostPort: 44318
      protocol: TCP
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false

  config:
    receivers:
      otlp:
        protocols:
          http:
            cors:
              allowed_origins:
                - "*"

    processors:
      batch:
        timeout: 5s

    exporters:
      debug/noop:
        verbosity: normal
        sampling_initial: 0
        sampling_thereafter: 0

      debug:
        verbosity: detailed
      
      otlp/jaeger:
        endpoint: pokeshop-jaeger-collector:4317
        tls:
          insecure: true

    service:
      pipelines:
        logs:
          exporters: [debug/noop]
          processors: [memory_limiter, batch]
          receivers: [otlp]
        metrics:
          exporters: [debug/noop]
          processors: [memory_limiter, batch]
          receivers: [otlp,prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]

jaeger:
  enabled: true
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true

  storage:
    type: memory

  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false
