apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jwt-sign-cert
spec:
  isCA: true
  commonName: {{ .Values.certManager.commonName }}
  secretName: {{ .Values.certManager.secretName }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: issuer-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
