apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest-cloud.fullname" . }}-config
  labels:
    {{- include "tracetest-cloud.labels" . | nindent 4 }}
data:
  AGENT_HOST: "{{ .Values.config.controlPlaneUrl }}"
  AGENT_PORT: "8091"
  ALLOWED_EXTERNAL_REDIRECT_URIS: "https://{{ .Values.config.webUIUrl }}"
  API_MONGO_DB: "{{ .Values.global.mongodb.auth.database }}"
  API_PUBLIC_ROUTES: "/webhook/login,/version,/health,/robots.txt"
  DASHBOARD_ADDRESS: "https://{{ .Values.config.webUIUrl }}"
  DEBUG: "true"
  DEV_MODE: "false"
  ENTERPRISE_MODE: "true"
  KETO_ADMIN_URL: "http://keto-write.ory"
  KETO_API_URL: "http://keto-read.ory"
  KRATOS_ADMIN_API_URL: "http://kratos-admin.ory"
  KRATOS_PUBLIC_API_URL: "http://kratos-public.ory"
  NATS_URI: "{{ .Values.global.nats.endpoint }}"
  OAUTH_ENABLED: "false"
  OSS_ENDPOINT: "http://tracetest.oss:11633"
  ROOT_DOMAIN: "tracetest.io"
  UI_ENDPOINT: "https://{{ .Values.config.webUIUrl }}"
  DEMO_ORG_ID: "{{ .Values.config.demoOrgID }}"
  DEMO_INVITE_ID: "{{ .Values.config.demoInviteID }}"
  DISABLE_TELEMETRY: "{{ not .Values.config.telemetry.enabled }}"
  COLLECTOR_ENDPOINT: "{{ .Values.config.telemetry.collector.endpoint }}"
  PROFILER_COLLECTOR_ENDPOINT: "{{ .Values.config.telemetry.profiler.endpoint }}"
  PROFILER_SAMPLING_PERCENTAGE: "{{ .Values.config.telemetry.profiler.samplingRate }}"
  PROFILER_ENVIRONMENT: "{{ .Values.config.telemetry.profiler.environment }}"