apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest-cloud.fullname" . }}-config
  labels:
    {{- include "tracetest-cloud.labels" . | nindent 4 }}
data:
  {{- $defaultKetoAdminUrl := (printf "http://%s-keto-write.%s" .Release.Name .Release.Namespace) }}
  {{- $defaultKetoApiUrl := (printf "http://%s-keto-read.%s" .Release.Name .Release.Namespace) }}
  {{- $defaultKratosAdminUrl := (printf "http://%s-kratos-admin.%s" .Release.Name .Release.Namespace) }}
  {{- $defaultKratosApiUrl := (printf "http://%s-kratos-public.%s" .Release.Name .Release.Namespace) }}

  {{- $ketoAdminUrl := (dig "auth" "keto" "adminUrl" $defaultKetoAdminUrl .Values.config  ) }}
  {{- $ketoApiUrl := (dig "auth" "keto" "apiUrl" $defaultKetoApiUrl .Values.config  ) }}
  {{- $kratosAdminUrl := (dig "auth" "kratos" "adminUrl" $defaultKratosAdminUrl .Values.config  ) }}
  {{- $kratosApiUrl := (dig "auth" "kratos" "apiUrl" $defaultKratosApiUrl .Values.config  ) }}

  AGENT_HOST: "{{ .Values.global.urls.controlPlane.hostname }}"
  AGENT_PORT: "8091"
  ALLOWED_EXTERNAL_REDIRECT_URIS: "{{ include "tracetest-common.url" .Values.global.urls.web }}"
  API_MONGO_DB: "{{ .Values.global.mongodb.auth.database }}"
  API_PUBLIC_ROUTES: "/webhook/login,/version,,/version.json,/health,/robots.txt"
  DASHBOARD_ADDRESS: "{{ include "tracetest-common.url" .Values.global.urls.web }}"
  DEBUG: "true"
  DEV_MODE: "true"
  ENTERPRISE_MODE: "true"
  KETO_ADMIN_URL: "{{- $ketoAdminUrl }}"
  KETO_API_URL: "{{- $ketoApiUrl }}"
  KRATOS_ADMIN_API_URL: "{{- $kratosAdminUrl }}"
  KRATOS_PUBLIC_API_URL: "{{- $kratosApiUrl }}"
  NATS_URI: {{ include "tracetest-common.nats_endpoint" . }}
  OAUTH_ENABLED: "false"
  OSS_ENDPOINT: "http://{{ .Release.Name }}-tracetest-core.{{ .Release.Namespace }}:{{ .Values.global.tracetestCore.service.httpPort }}"
  ROOT_DOMAIN: "{{ .Values.global.urls.rootDomain }}"
  UI_ENDPOINT: "{{ include "tracetest-common.url" .Values.global.urls.web }}"
  DEMO_ORG_ID: "{{ .Values.config.demoOrgID }}"
  DEMO_INVITE_ID: "{{ .Values.config.demoInviteID }}"
  DISABLE_TELEMETRY: "{{ not .Values.config.telemetry.enabled }}"
  COLLECTOR_ENDPOINT: "{{ .Values.config.telemetry.collector.endpoint }}"
  PROFILER_COLLECTOR_ENDPOINT: "{{ .Values.config.telemetry.profiler.endpoint }}"
  PROFILER_SAMPLING_PERCENTAGE: "{{ .Values.config.telemetry.profiler.samplingRate }}"
  PROFILER_ENVIRONMENT: "{{ .Values.config.telemetry.profiler.environment }}"