---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "tracetest-cloud.fullname" . }}-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "tracetest-cloud.fullname" . }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.config.apiUrl }}`)
    middlewares:
    - name: {{ include "tracetest-cloud.fullname" . }}-stripprefix
    services:
    - kind: Service
      name: {{ include "tracetest-cloud.fullname" . }}
      passHostHeader: true
      port: cloud-api-http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: control-plane
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.config.apiUrl }}`) && Headers(`Content-Type`, `application/grpc`)
    services:
    - kind: Service
      name: {{ include "tracetest-cloud.fullname" . }}
      passHostHeader: true
      port: control-plane
      scheme: h2c


---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: control-plane-custom-port
spec:
  entryPoints:
    - controlplane
  routes:
  - kind: Rule
    match: Host(`{{ .Values.config.apiUrl }}`)
    services:
    - kind: Service
      name: {{ include "tracetest-cloud.fullname" . }}
      passHostHeader: true
      port: control-plane
      scheme: h2c
