---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "tracetest-cloud.fullname" . }}-stripprefix
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.global.urls.api.path }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "tracetest-cloud.fullname" . }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.global.urls.api.hostname }}`) && PathPrefix(`{{ .Values.global.urls.api.path }}`)
    middlewares:
    - name: {{ include "tracetest-cloud.fullname" . }}-stripprefix
    services:
    - kind: Service
      name: {{ include "tracetest-cloud.fullname" . }}
      passHostHeader: true
      port: cloud-api-http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: control-plane
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.global.urls.api.hostname }}`) && Headers(`Content-Type`, `application/grpc`)
    services:
    - kind: Service
      name: {{ include "tracetest-cloud.fullname" . }}
      passHostHeader: true
      port: control-plane
      scheme: h2c
