---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracetest-cloud.fullname" . }}-secrets
  labels:
    {{- include "tracetest-cloud.labels" . | nindent 4 }}
type: Opaque
data:
  API_MONGO_DSN: {{ include "tracetest-cloud.mongodb_dsn" . | b64enc }}
  POSTGRES_CONN: {{ include "tracetest-cloud.postgres_dsn" . | b64enc }}
  SENDGRID_API_KEY: {{ .Values.config.sendgridApiKey | b64enc }}
  HUBSPOT_API_KEY: {{ .Values.config.hubspotApiKey | b64enc }}
  SEGMENTIO_WRITE_KEY: {{ .Values.config.segmentWriteKey | b64enc }}
