apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracetest-cloud.fullname" . }}
  labels:
    {{- include "tracetest-cloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: cloud-api-grpc
      targetPort: cloud-api-grpc
      protocol: TCP
      port: {{ .Values.service.grpcPort }}
    - name: cloud-api-http
      targetPort: cloud-api-http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
    - name: control-plane
      targetPort: control-plane
      protocol: TCP
      port: {{ .Values.service.controlPlanePort }}
    - name: metrics
      targetPort: metrics
      protocol: TCP
      port: {{ .Values.service.metricsPort }}
  selector:
    {{- include "tracetest-cloud.selectorLabels" . | nindent 4 }}
