global:
  # URLs section with addresses used by clients to connect to the Tracetest OnPrem instance
  urls:
    rootDomain: &rootDomain "tracetest.localdev"
    
    otlpingest:
      hostname: *rootDomain

opentelemetry-collector:
  nameOverride: public-endpoint-otel-collector

  mode: deployment

  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.111.0"

  ports:
    otlp:
      enabled: true
    otlp-http:
      enabled: true
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
    metrics:
      enabled: false

  config:
    receivers:
      otlp:
        protocols:
          grpc:
            max_recv_msg_size_mib: 20 # 10 MiB
          http:
            max_request_body_size: 40971520

    processors:
      batch:
        send_batch_size: 1024
        send_batch_max_size: 2048
        timeout: 500ms

    exporters:
      debug:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]

        # TODO: due to an issue on Helm (https://github.com/open-telemetry/opentelemetry-helm-charts/issues/223#issuecomment-1697239843)
        # we are not able to disable metrics and logs pipeline when OTel Collector is a subchart
        # so we are defining them as simple as possible
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]