opentelemetry-collector:
  nameOverride: public-endpoint-otel-collector

  mode: deployment

  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.111.0"

  ports:
    otlp:
      enabled: true
    otlp-http:
      enabled: true
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false

  config:
    receivers:
      otlp:
        protocols:
          grpc:
            max_recv_msg_size_mib: 20 # 10 MiB
          http:
            max_request_body_size: 40971520

    processors:
      batch/traces:
        send_batch_size: 1024
        send_batch_max_size: 2048
        timeout: 500ms

    exporters:
      debug:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [debug]

        metrics: {}

        logs: {}