global:
  licenseKey: ""
  imagePullSecret: ""
  tracetestImageRegistry: ""
  replicasPerService: 1

  tracetestCore:
    service:
      httpPort: &httpPort 11633

  nats:
    endpoint: "nats://nats:4222"

  postgresql:
    auth:
      username: ""
      password: ""
      database: ""
      port: "5432"

config:
  tracetestAnalyticsServerKey: some-value
  tracetestSecurityEncryptionKey: some-value
  profiler:
    samplingRate: 50
    endpoint: some-value
    environment: development

  analytics: false

server:
  httpPort: *httpPort


image:
  repository: kubeshop/tracetest-core

deployments:
  - name: api
    env:
      TRACETEST_SERVER_API_ENABLED: true
      TRACETEST_SERVER_WORKFLOW_ENABLED: false

  - name: worker-trigger
    env:
      TRACETEST_SERVER_API_ENABLED: false
      TRACETEST_SERVER_WORKFLOW_ENABLED: true
      TRACETEST_SERVER_WORKFLOW_STEPS: trigger_resolver trigger_result
  - name: worker-poller
    env:
      TRACETEST_SERVER_API_ENABLED: false
      TRACETEST_SERVER_WORKFLOW_ENABLED: true
      TRACETEST_SERVER_WORKFLOW_STEPS: poll_start poll_evaluate
  - name: worker-results
    env:
      TRACETEST_SERVER_API_ENABLED: false
      TRACETEST_SERVER_WORKFLOW_ENABLED: true
      TRACETEST_SERVER_WORKFLOW_STEPS: linter_runner assertion_runner
  - name: worker-monitors
    env:
      TRACETEST_SERVER_API_ENABLED: false
      TRACETEST_SERVER_WORKFLOW_ENABLED: true
      TRACETEST_SERVER_WORKFLOW_STEPS: monitor_runner monitor_alerts
  - name: worker-suites
    env:
      TRACETEST_SERVER_API_ENABLED: false
      TRACETEST_SERVER_WORKFLOW_ENABLED: true
      TRACETEST_SERVER_WORKFLOW_STEPS: suite_runner