---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pokeshop-demo.fullname" . }}-http
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.hostname }}`)
    services:
    - kind: Service
      name: {{ include "pokeshop-demo.fullname" . }}-api
      passHostHeader: true
      port: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pokeshop-demo.fullname" . }}-grpc
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.hostname }}`) && Headers(`Content-Type`, `application/grpc`)
    services:
    - kind: Service
      name: {{ include "pokeshop-demo.fullname" . }}-api
      passHostHeader: true
      port: grpc
      scheme: h2c
