{{- if .Values.pokeshop.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "pokeshop-demo.fullname" . }}-stream
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`*`)
    services:
    - name: stream
      port: plaintext
{{- end }}