# ---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: {{ include "pokeshop-demo.fullname" . }}-otel-collector-stripprefix
# spec:
#   stripPrefix:
#     prefixes:
#       - /otc
# ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pokeshop-demo.fullname" . }}-otel-collector
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/v1/traces`)
    services:
    - kind: Service
      name: {{ .Release.Name }}-opentelemetry-collector
      passHostHeader: true
      port: otlp-http
      # middlewares:
      # - name: {{ include "pokeshop-demo.fullname" . }}-otel-collector-stripprefix
