{{- if .Values.pokeshop.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pokeshop-demo.fullname" . }}-otel-collector
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.pokeshop.ingress.hostname }}`) && PathPrefix(`/v1/traces`)
    services:
    - kind: Service
      name: {{ .Release.Name }}-opentelemetry-collector
      passHostHeader: true
      port: otlp-http
{{- end }}