apiVersion: v1
kind: Service
metadata:
  name: stream
  labels:
    {{- include "pokeshop-demo.stream.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: plaintext
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: controller
      port: 9093
      protocol: TCP
      targetPort: 9093

  selector:
    {{- include "pokeshop-demo.stream.selectorLabels" . | nindent 4 }}
