apiVersion: v1
kind: Service
metadata:
  name: {{ include "pokeshop-demo.fullname" . }}-api
  labels:
    {{- include "pokeshop-demo.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pokeshop.service.type }}
  ports:
    - port: {{ .Values.pokeshop.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
    - port: {{ .Values.pokeshop.service.rpcPort }}
      targetPort: 8082
      protocol: TCP
      name: grpc
  selector:
    {{- include "pokeshop-demo.api.selectorLabels" . | nindent 4 }}
