global:
  nats:
    endpoint: &natsEndpoint "nats://nats:4222"
  urls:
    controlPlaneUrl: &controlPlaneUrl "https://control-plane.tracetest.io"
    agentsDomain: &agentsDomain "agents.example.com"

config:
  natsEndpoint: *natsEndpoint
  targetVersion: v0.0.0
  targetNamespace: agents
  targetServer: *controlPlaneUrl
  targetDomain: *agentsDomain

service:
  type: ClusterIP
  grpcPort: 8089
  httpPort: 8090
  controlPlanePort: 8091
  metricsPort: 9100

deployment:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

image:
  repository: ghcr.io/kubeshop/tracetest-agent-operator
  # tag: v0.1.0

