apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest-agent-operator.fullname" . }}-config
  labels:
    {{- include "tracetest-agent-operator.labels" . | nindent 4 }}
data:
  TRACETEST_NATS_ENDPOINT: "{{ .Values.global.nats.endpoint }}"
  TRACETEST_TARGET_VERSION: "{{ .Values.global.targetVersion }}"
  TRACETEST_TARGET_NAMESPACE: "{{ .Values.config.targetNamespace }}"
  TRACETEST_TARGET_SERVER: "{{ .Values.config.targetServer }}"
  TRACETEST_TARGET_DOMAIN: "{{ .Values.config.targetDomain }}"
  TRACETEST_TRACING_COLLECTORENDPOINT: ""
