apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest-agent-operator.fullname" . }}-config
  labels:
    {{- include "tracetest-agent-operator.labels" . | nindent 4 }}
data:
  TRACETEST_NATS_ENDPOINT: "{{ .Values.config.natsEndpoint }}"
  TRACETEST_TARGET_VERSION: "{{ .Values.config.targetVersion }}"
  TRACETEST_TARGET_NAMESPACE: "{{ .Values.config.targetNamespace }}"
  TRACETEST_TARGET_SERVER: "{{ .Values.config.targetServer }}"
  TRACETEST_TARGET_DOMAIN: "{{ .Values.config.targetDomain }}"
  TRACETEST_TRACING_COLLECTORENDPOINT: "collector-opentelemetry-collector.otel:4317"
  # TRACETEST_TRACING_COLLECTORENDPOINT: ""
