apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest-agent-operator.fullname" . }}-config
  labels:
    {{- include "tracetest-agent-operator.labels" . | nindent 4 }}
data:
  TRACETEST_NATS_ENDPOINT: {{ include "tracetest-common.nats_endpoint" . }}
  TRACETEST_TARGET_VERSION: "{{ .Values.config.targetVersion }}"
  TRACETEST_TARGET_NAMESPACE: "{{ .Values.config.targetNamespace }}"
  TRACETEST_TARGET_SERVER: {{ include "tracetest-common.url" .Values.global.urls.api }}
  TRACETEST_TARGET_DOMAIN: "{{ .Values.global.urls.agents.domain }}"
  TRACETEST_AGENT_EXTRA_ENV: ""
  # TRACETEST_AGENT_EXTRA_ENV: |
  #   TRACETEST_ALLOW_INSECUE
  TRACETEST_TRACING_COLLECTORENDPOINT: ""
  TRACETEST_AGENT_SKIP_VERIFY: "{{ not .Values.global.validCertificate }}"
