apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tracetest-agent-operator.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tracetest-agent-operator.fullname" . }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tracetest-agent-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tracetest-agent-operator.fullname" . }}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{ include "tracetest-agent-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
