global:
  imagePullSecret: ""
  tracetestImageRegistry: ""
  validCertificate: true
  
  nats:
    endpoint: "nats://nats:4222"

  urls:
    api:
      protocol: "https"
      hostname: "tracetest.localdev"
      port: "30000"
      path: "/api"

config:
  targetNamespace: monitors
  telemetry:
    collector:
      endpoint: ""

deployment:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

image:
  repository: kubeshop/tracetest-monitor-operator


