global:
  imagePullSecret: ""
  tracetestImageRegistry: ""
  
  nats:
    endpoint: "nats://nats:4222"

  urls:
    web:
      protocol: "https"
      hostname: "tracetest.localdev"
      port: "30000"
      path: "/"

config:
  targetNamespace: monitors
  # collectorEndpoint: "collector-opentelemetry-collector.otel:4317"
  collectorEndpoint: ""

deployment:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

image:
  repository: kubeshop/tracetest-monitor-operator


