{{- if .Values.agent.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracetest-agent.fullname" . }}-secret
  labels:
    {{- include "tracetest-agent.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.agent.apiKey | b64enc | quote }}
{{- end }}