apiVersion: v1
kind: ConfigMap
metadata:
  name: keto-custom-config
  labels:
    {{- include "ory-kratos.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/keto/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: keto-custom-config
  labels:
    {{- include "ory-kratos.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/kratos*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}

