apiVersion: v1
kind: ConfigMap
metadata:
  name: keto-namespace-config
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/keto/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-custom-config
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/kratos/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracetest-auth-config
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  COOKIES_DOMAIN: {{ .Values.oathkeeper.global.cookieDomain }}
  ISSUER_URL: https://{{ .Values.global.urls.apiDomain }}/auth
  BASE_AUTH_URL: https://{{ .Values.global.urls.apiDomain }}/auth
  DEFAULT_BROWSER_RETURN_URL: https://{{ .Values.global.urls.webDomain }}/
  ERROR_UI_URL: https://{{ .Values.global.urls.webDomain }}/error
  LOGIN_URL: https://{{ .Values.global.urls.apiDomain }}/oathkeeper/login
  LOGIN_AFTER_HOOK_URL: https://{{ .Values.global.urls.apiDomain }}/api/webhook/login
  CORS_ALLOWED_ORIGINS: '["https://{{ .Values.global.urls.webDomain }}"]' #this must be in json format

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracetest-oathkeeper-rules
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  access-rules.yml: |-
    - id: "ory:kratos:public"
      upstream:
        preserve_host: true
        url: "http://kratos-public.ory"
        strip_path: /auth
      match:
        url: "https://{{ .Values.global.urls.apiDomain }}/auth/<**>"
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
      authenticators:
        - handler: noop
      authorizer:
        handler: allow
      mutators:
        - handler: noop