apiVersion: v1
kind: ConfigMap
metadata:
  name: keto-namespace-config
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/keto/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-custom-config
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/kratos/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracetest-auth-config
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  COOKIES_DOMAIN: {{ .Values.global.urls.cookieDomain }}
  ISSUER_URL: {{ include "tracetest-common.url" .Values.global.urls.auth }}
  BASE_AUTH_URL: {{ include "tracetest-common.url" .Values.global.urls.auth }}
  DEFAULT_BROWSER_RETURN_URL: {{ include "tracetest-common.url" .Values.global.urls.web }}
  ERROR_UI_URL: {{ include "tracetest-common.url" .Values.global.urls.web }}/error
  LOGIN_URL: {{ include "tracetest-common.url" .Values.global.urls.auth }}/oathkeeper/login
  LOGIN_AFTER_HOOK_URL: http://{{ .Release.Name }}-tracetest-cloud.{{ .Release.Namespace }}:{{ .Values.global.tracetestCloud.service.httpPort}}/webhook/login
  CORS_ALLOWED_ORIGINS: '["{{ include "tracetest-common.url" .Values.global.urls.web }}"]' #this must be in json format

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracetest-oathkeeper-rules
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  access-rules.yml: |-
    - id: "ory:kratos:public"
      upstream:
        preserve_host: true
        url: "http://{{ .Release.Name }}-kratos-public.{{ .Release.Namespace }}"
        strip_path: /auth
      match:
        url: "{{ include "tracetest-common.url" .Values.global.urls.auth }}/<**>"
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
      authenticators:
        - handler: noop
      authorizer:
        handler: allow
      mutators:
        - handler: noop