apiVersion: v1
kind: Secret
metadata:
  name: oathkeeper-secrets
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/oathkeeper/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4  | b64enc}}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: keto-secrets
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  DSN: {{ include "tracetest-auth.postgres_dsn" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kratos-secrets
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  DSN: {{ include "tracetest-auth.postgres_dsn" . | b64enc }}
  COOKIE: {{ randAlphaNum 32 | b64enc }}
  CIPHER: {{ randAlphaNum 32 | b64enc }}
  SMTP_URI: {{ .Values.global.smtp.uri | b64enc }}