apiVersion: v1
kind: Secret
metadata:
  name: oathkeeper-secrets
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/oathkeeper/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc | nindent 4 }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: keto-secrets
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  DSN: {{ include "tracetest-auth.keto_postgres_dsn" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kratos-secrets
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  dsn: {{ include "tracetest-auth.kratos_postgres_dsn" . | b64enc }}
  secretsCipher: {{ randAlphaNum 32 | b64enc }}
  secretsCookie: {{ randAlphaNum 32 | b64enc }}
  secretsDefault: {{ randAlphaNum 32 | b64enc }}
  smtpConnectionURI: {{ .Values.global.smtp.uri | b64enc }}
  # DSN: {{ include "tracetest-auth.kratos_postgres_dsn" . | b64enc }}
  # COOKIE: {{ randAlphaNum 32 | b64enc }}
  # CIPHER: {{ randAlphaNum 32 | b64enc }}
  # SMTP_URI: {{ .Values.global.smtp.uri | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.global.sso.google.clientID | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.global.sso.google.clientSecret | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.global.sso.github.clientID | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.global.sso.github.clientSecret | b64enc | quote }}