apiVersion: v1
kind: Secret
metadata:
  name: oathkeeper-custom-config
  labels:
    {{- include "tracetest-auth.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "config/oathkeeper/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4  | b64enc}}
  {{- end }}
