apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "tracetest-cloud.fullname" . }}-cors
spec:
  headers:
    accessControlAllowHeaders:
      - '*'
    accessControlAllowMethods:
      - '*'
    accessControlAllowOriginList:
      - '*'
    accessControlMaxAge: 100
    addVaryHeader: true