---
apiVersion: v1
kind: Secret
metadata:
  name: tracetest-nats-credentials
  labels:
    {{- include "tracetest-onprem.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  username: {{ .Values.nats.credentials.username | b64enc }}
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $password to existing secret data or generate a random one when not exists
  {{- $password := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
  password: {{ $password | quote }}