---
apiVersion: v1
kind: Secret
metadata:
  name: tracetest-nats-credentials
  labels:
    {{- include "tracetest-onprem.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.nats.credentials.username | b64enc }}
  password: {{ randAlphaNum 32 | b64enc }}
