{{- if ".Values.cert-manager.enabled" }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-selfsigned
  labels:
  {{- include "tracetest-dependencies.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}