{{- if .Values.mongodb.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tracetest-dependencies.fullname" . }}-mongodb
  labels:
    {{- include "tracetest-dependencies.labels" . | nindent 4 }}
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      {{- include "tracetest-dependencies.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/mongodb-credentials.yaml") . | sha256sum }}
      labels:
        {{- include "tracetest-dependencies.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.12
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "tracetest-dependencies.fullname" . }}-mongodb-credentials
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "tracetest-dependencies.fullname" . }}-mongodb-credentials
              key: password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "tracetest-dependencies.fullname" . }}-mongodb-credentials
              key: database
  volumeClaimTemplates:
  - metadata:
      name: {{ include "tracetest-dependencies.fullname" . }}-mongodb-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracetest-dependencies.fullname" . }}-mongodb
  labels:
    {{- include "tracetest-dependencies.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    {{- include "tracetest-dependencies.selectorLabels" . | nindent 4 }}

{{- end }}
