{{- if .Values.mongodb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracetest-dependencies.fullname" . }}-mongodb-credentials
type: Opaque
stringData:
  username: {{ .Values.global.mongodb.auth.username }}
  password: {{ .Values.global.mongodb.auth.password }}
  database: {{ .Values.global.mongodb.auth.database }}
{{- end }}
