{{- if .Values.traefik.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "tracetest-dependencies.fullname" . }}-cert
  labels:
  {{- include "tracetest-dependencies.labels" . | nindent 4 }}
spec:
  secretName: {{ include "tracetest-dependencies.fullname" . }}-cert
  issuerRef:
    name: {{ .Values.traefik.tls.issuerRef.name }}
    kind: {{ .Values.traefik.tls.issuerRef.kind }}
    group: {{ .Values.traefik.tls.issuerRef.group }}

  dnsNames:
  {{- range .Values.traefik.dnsNames }}
    - {{ . | quote }}
  {{- end }}

---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  labels:
  {{- include "tracetest-dependencies.labels" . | nindent 4 }}
spec:
  certificates:
    - secretName: {{ include "tracetest-dependencies.fullname" . }}-cert
  defaultCertificate:
    secretName: {{ include "tracetest-dependencies.fullname" . }}-cert
{{- end }}