global:
  imagePullSecret: ""
  
postgres:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  dbname: "tracetest"

jwtSignCert:
  commonName: jwt-sign-cert
  secretName: jwt-sign-cert
  issuerRef:
    name: issuer-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io

service:
  type: ClusterIP
  grpcPort: 8089
  httpPort: 8090
  controlPlanePort: 8091
  metricsPort: 9100

deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi

image:
  repository: ghcr.io/kubeshop/tracetest-cloud
  # tag: v1.2.0

config:
  webUIUrl: some-url
  apiUrl: some-url
  controlPlaneUrl: some-value
  mongodbDSN: some-value
  sendgridApiKey: some-value
  githubCredential: some-credential-string
  hubspotApiKey: some-value
  segmentWriteKey: some-value

  profiler:
    samplingRate: 50
    endpoint: ""
    environment: development

  demoOrgID: some-value
  demoInviteID: some-value
