global:
  licenseKey: ""
  imagePullSecret: ""
  tracetestImageRegistry: ""

  tracetestCore:
    service:
      httpPort: 11633
      otlpGrpcPort: 4317

  tracetestCloud:
    service:
      grpcPort: &grpcPort 8089
      httpPort: &httpPort 8090
      controlPlanePort: &controlPlanePort 8091
      metricsPort: &metricsPort 9100
      otlpGrpcPort: &otlpGrpcPort 4317
      otlpHttpPort: &otlpHttpPort 4318

  urls:
    rootDomain: "tracetest.localdev"
    web:
      protocol: "https"
      hostname: "tracetest.localdev"
      port: "30000"
      path: "/"
    
    api:
      protocol: "https"
      hostname: "tracetest.localdev"
      port: "30000"
      path: "/api"
    
    agents:
      domain: "tracetest.localdev"
      port: "30000"

    controlPlane:
      hostname: "tracetest.localdev"
      port: "30000"

  mongodb:
    auth:
      protocol: "mongodb"
      host: ""
      username: ""
      password: ""
      database: ""
      options: {}
  
  postgresql:
    auth:
      host: "postgres"
      user: "postgres"
      password: "postgres"
      dbname: "tracetest"
      port: "5432"

jwtSignCert:
  commonName: jwt-sign-cert
  secretName: jwt-sign-cert
  issuerRef:
    name: issuer-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io

service:
  type: ClusterIP
  grpcPort: *grpcPort
  httpPort: *httpPort
  controlPlanePort: *controlPlanePort
  metricsPort: *metricsPort
  otlpGrpcPort: *otlpGrpcPort
  otlpHttpPort: *otlpHttpPort

deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi

image:
  repository: kubeshop/tracetest-cloud
  pullPolicy: IfNotPresent

config:
  sendgridApiKey: some-value
  githubCredential: some-credential-string
  hubspotApiKey: some-value
  segmentWriteKey: some-value
  
  # Uncomment the following block to enable custom Auth with Ory Kratos and Keto
  # auth:
  #   kratos:
  #     adminUrl: ""
  #     apiUrl: ""
  #   keto:
  #     adminUrl: ""
  #     apiUrl: ""

  telemetry:
    enabled: false
    collector:
      endpoint: ""
    
    profiler:
      samplingRate: 50
      endpoint: ""
      environment: development

  demoOrgID: some-value
  demoInviteID: some-value
