certManager:
  commonName: jwt-sign-cert
  secretName: jwt-sign-cert

service:
  type: ClusterIP
  grpcPort: 8089
  httpPort: 8090
  controlPlanePort: 8091
  metricsPort: 9100

deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi

imagePullSecrets: ghcr-credentials

image:
  repository: ghcr.io/kubeshop/tracetest-cloud
  tag: v1.0.0

config:
  webUIUrl: some-url
  apiUrl: some-url
  controlPlaneUrl: some-value
  mongodbDSN: some-value
  postgresConn: some-value
  sendgridApiKey: some-value
  githubCredential: some-credential-string
  hubspotApiKey: some-value
  segmentWriteKey: some-value
  profilerEndpoint: some-value
  profilerEnvironment: development
  profilerSamplingRate: 50
  demoOrgID: some-value
  demoInviteID: some-value
