name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    env:
      TRACETEST_LICENSE: ${{ secrets.TRACETEST_ONPREM_TEST_LICENSE }}
      AGENT_API_KEY: ${{ secrets.AGENT_API_KEY }}
      AGENT_ENV_ID: ${{ secrets.AGENT_ENV_ID }}
      TESTS_REPO_DIR: "/tmp/tests"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup KinD
        uses: helm/kind-action@v1
        with:
          cluster_name: tracetest
          install_only: true

      - name: Test public images
        run: |
          kubectl config get-contexts
          ./scripts/setup_kind_cluster.sh --ci --build-deps  --install-demo --force-setup
          
          kind get kubeconfig --name tracetest > ~/.kube/config

          kubectl wait --for=condition=available --timeout=60s deployment/cloudagent-tracetest-agent
          echo "Cloudagent deployed"

      - name: Configure Custom DNS
        run: |
          # setup custom DNS resolve
          sudo echo "127.0.0.1 tracetest.localdev" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 pokeshop.localdev" | sudo tee -a /etc/hosts

      - name: Install Playwright
        run: |
          npx playwright install --with-deps
      
      - name: Configure intial org and env
        env:
          TRACETEST_TEST_REPO_CLONE_PAT: ${{ secrets.TRACETEST_TEST_REPO_CLONE_PAT }}
          TRACETEST_TEST_REPO: ${{ secrets.TRACETEST_TEST_REPO }}
          GH_USERNAME: ${{ secrets.TRACETEST_USER_GH_USERNAME }}
          GH_PASSWORD: ${{ secrets.TRACETEST_USER_GH_PASSWORD }}
          GH_SECRET: ${{ secrets.TRACETEST_USER_GH_SECRET }}
          TRACETEST_ENDPOINT: https://tracetest.localdev:30000/
          OUTPUT_TOKEN_FILE: "/tmp/token.json"
        run: |
          BASEDIR=$(pwd)

          # sparse checkout of the testing directory
          git clone https://$TRACETEST_TEST_REPO_CLONE_PAT@github.com/$TRACETEST_TEST_REPO.git $TESTS_REPO_DIR
          
          ./scripts/prepare_ci_env.sh

      - name: Configure Tracetest CLI
        uses: kubeshop/tracetest-github-action@v1
        with:
          token: ${{secrets.TRACETEST_CLI_TOKEN}}
      
      - name: run tracetests
        run: |
          tracetest run testsuite -f $TESTS_REPO_DIR/testing/server-tracetesting/features --vars ./tests/vars/ci.yaml