name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install pybump
        run: |
          python3 -m pip install --upgrade pip
          pip install pybump

      - name: Update Helm deps
        run: bash scripts/update_helm_repos.sh

      - name: Bump Chart Versions
        run: bash scripts/bump_charts.sh

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
      
      - name: Copy documentation to gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          git checkout main -- README.md LICENSE docs
          git add README.md LICENSE docs
          git commit -m "Update documentation" || echo "No changes to commit"
          git push origin gh-pages